# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'


steps:

  - powershell: ls 
    displayName: Where Am I
  - powershell: write-host Build.ArtifactStagingDirectory:$(Build.ArtifactStagingDirectory)
    displayName: Artifact Locations
  - powershell: write-host System.DefaultWorkingDirectory:$(System.DefaultWorkingDirectory)
    displayName: Artifact Locations
  - powershell: write-host Build.BuildNumber:$(Build.BuildNumber)
    displayName: Build.BuildNumber


  - task: UseDotNet@2
    displayName: 'Use dotnet sdk 2.1.x'
    inputs:
      version: 2.1.x
      includePreviewVersions: false
  - task: UseDotNet@2
    displayName: 'Use dotnet sdk 3.x'
    inputs:
      version: 3.x
      includePreviewVersions: false


  - powershell: dotnet tool install --global AzureSignTool --version 2.0.17  
    displayName: Install AzureSignTool

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'



  - powershell: ./windows-native-signing/sign.ps1 -clientId $(AZURE_CLIENT_ID) -clientSecret $(AZURE_CLIENT_SECRET)

  - task: CopyFiles@2
    displayName: 'Copy Signed Files'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/windows-native-signing/x64'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/x64'
  
  - powershell: ./windows-native-signing/nuget-pack.ps1 -version $(Build.BuildNumber) 
    displayName: 'Nuget Pack Artifacts'

  - task: CopyFiles@2
    displayName: 'Copy Signed Files'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/windows-native-signing/nuget'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/nuget'

  
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop' 
    #publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional  
    #fileCopyOptions: #Optional

  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'windows-demo-feed'


